# Generated by Django 5.1.3 on 2024-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_orderitem_payment_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Canceled')], default=1),
        ),
    ]
