# Generated by Django 5.1.3 on 2024-12-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line_2',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.IntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Credit/Debit Card'), (3, 'UPI')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed')], default=1),
        ),
    ]
