# Generated by Django 5.1.3 on 2025-01-06 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_cart_final_price_cart_temporary_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='used_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
