# Generated by Django 5.1.3 on 2025-01-06 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0009_alter_coupon_discount_value'),
        ('cart', '0015_alter_usercoupon_used_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_custom.coupon'),
        ),
    ]
