# Generated by Django 5.1.3 on 2025-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.IntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Razor Pay'), (3, 'wallet')], default=1),
        ),
    ]
