# Generated by Django 5.1.3 on 2025-01-13 22:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
