# Generated by Django 5.1.3 on 2025-01-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0014_alter_offer_name'),
        ('cart', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_order', to='admin_custom.product'),
        ),
    ]
