# Generated by Django 5.1.3 on 2025-02-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0015_alter_productimage_image'),
        ('cart', '0021_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_product', to='admin_custom.product'),
        ),
    ]
