# Generated by Django 5.1.3 on 2024-12-17 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_background', to='admin_custom.product')),
            ],
        ),
    ]
