# Generated by Django 5.1.3 on 2025-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0007_alter_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the coupon', max_length=50, unique=True)),
                ('discount_type', models.IntegerField(choices=[(1, 'Percentage'), (2, 'Fixed Amount'), (3, 'Free Shipping')])),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value of the discount', max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True, help_text='Set to False to deactivate the coupon')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Tracks how many times the coupon has been used')),
            ],
            options={
                'ordering': ['-end_date', 'code'],
            },
        ),
    ]
