# Generated by Django 5.1.3 on 2025-01-06 01:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0008_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Value of the discount', max_digits=10, null=True),
        ),
    ]
