# Generated by Django 5.1.3 on 2025-01-08 04:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0009_alter_coupon_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='cap amount for each discount value', max_digits=10, null=True),
        ),
    ]
