# Generated by Django 5.1.3 on 2025-01-08 12:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0010_coupon_cap_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cap_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='cap amount for each discount value', max_digits=10, null=True),
        ),
    ]
