# Generated by Django 5.1.3 on 2025-01-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0012_offer_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='priority',
        ),
    ]
