# Generated by Django 5.1.3 on 2025-01-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0013_alter_offer_options_remove_offer_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
