# Generated by Django 5.1.3 on 2024-12-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdata_is_active_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Work')], default=1, max_length=20),
        ),
    ]
