# Generated by Django 5.1.3 on 2024-12-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
